/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageOrderJPanel extends javax.swing.JPanel {

    private UserAccount userAccount;
    private Enterprise enterprise;
    private Network network;
    private EcoSystem ecoSystem;
    private JPanel userProcessContainer;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrderJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.network = network;
        this.ecoSystem = ecoSystem;
        
        populateTable();
        populateCombo();
        populateBtn();
    }
    
    private void populateBtn(){
         if (enterprise.getEnterpriseType().toString().equals("Fitness")) {
            seekBtn.setVisible(false);
            acceptBtn.setVisible(true);
            enterpriseJComboBox.setVisible(false);
            jLabel1.setVisible(false);
        }
        else if (enterprise.getEnterpriseType().toString().equals("Market")) {
            seekBtn.setVisible(true);
            acceptBtn.setVisible(false);
        }
        else if (enterprise.getEnterpriseType().toString().equals("PhysicalTherapy")) {
            seekBtn.setVisible(true);
            acceptBtn.setVisible(false);
        }
    }
    
    private void populateCombo(){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
            //show other type enterprise
            if (e.getEnterpriseType().toString().equals("Fitness")){
                enterpriseJComboBox.addItem(e);
            }
        }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) orderJTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = workRequest;
            row[1] = workRequest.getSender();
            row[2] = workRequest.getRequestDate();
            row[3] = workRequest.getStatus();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        acceptBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        seekBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(111, 158, 159));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderJTable);
        if (orderJTable.getColumnModel().getColumnCount() > 0) {
            orderJTable.getColumnModel().getColumn(0).setResizable(false);
            orderJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 113, 547, 250));

        acceptBtn.setBackground(new java.awt.Color(255, 255, 255));
        acceptBtn.setText(" Accept Cooperation");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });
        add(acceptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 421, 163, 60));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 501, -1, 60));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Enterprise ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 381, -1, -1));

        enterpriseJComboBox.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 382, 163, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Manage Cooperation");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 45, -1, -1));

        seekBtn.setBackground(new java.awt.Color(255, 255, 255));
        seekBtn.setText("Seek Cooperation");
        seekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seekBtnActionPerformed(evt);
            }
        });
        add(seekBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 421, -1, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed

        int selectedOrder = orderJTable.getSelectedRow();

        if (selectedOrder < 0){
            JOptionPane.showMessageDialog(null, "Please select an order from table", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //save coop info
            WorkRequest request = (WorkRequest) orderJTable.getValueAt(selectedOrder, 0);
            String message = request.getMessage();
            String[] ss = message.split(" ");
            Enterprise senderEnterprise = network.getEnterpriseDirectory().getEnterpriseByName(ss[ss.length-1]);
            enterprise.getCoopEnterpriseDirectory().getEnterpriseList().add(senderEnterprise);
            
            userAccount.getWorkQueue().getWorkRequestList().remove(request);
            JOptionPane.showMessageDialog(null, "Cooperation Accepted!");
            DB4OUtil.getInstance().storeSystem(ecoSystem);
            populateTable();
        }

    }//GEN-LAST:event_acceptBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    private void seekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seekBtnActionPerformed
        // Find receive manager useraccount
        Enterprise receiveEnterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        UserAccount receiveAccount = receiveEnterprise.getManagerUserAccount();
        
        WorkRequest workRequest = new WorkRequest();
        workRequest.setMessage(enterprise.getEnterpriseType() + " Company: " + enterprise.getName());
        workRequest.setReceiver(receiveAccount);
        workRequest.setSender(userAccount);
        workRequest.setRequestDate(new Date());
        workRequest.setStatus("Asking");
        
        userAccount.getWorkQueue().getWorkRequestList().add(workRequest);
        receiveAccount.getWorkQueue().getWorkRequestList().add(workRequest);
        JOptionPane.showMessageDialog(null, "Seek Cooperation request send!");
        populateTable();
    }//GEN-LAST:event_seekBtnActionPerformed
    
//    private UserAccount getManagerUserAccount(Enterprise enterprise) {
//        for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
//            if (ua.getRole().toString() == "Business.Role.ManagerRole") {
//                return ua;
//            }
//        }
//        return null;
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderJTable;
    private javax.swing.JButton seekBtn;
    // End of variables declaration//GEN-END:variables
}
